@baseURL=http://localhost:5005/api


# GET ALL USERS
GET {{baseURL}}/users

### GET USER BY ID
GET {{baseURL}}/users/1

### GET SALES OF USER BY ID 
GET {{baseURL}}/users/2/sales

### GET USER BY TAG
GET {{baseURL}}/users/search?tag=matt

### ERROR ROUTE

GET {{baseURL}}/3